// Schema factory that creates the appropriate schema based on database type
import { pgTable, varchar as pgVarchar, text as pgText, integer as pgInteger } from 'drizzle-orm/pg-core';
import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';

export function createSchema(dbType) {
  if (dbType === 'postgres') {
    return {
      users: pgTable('users', {
        id: pgVarchar('id', { length: 255 }).primaryKey(),
        name: pgVarchar('name', { length: 255 }).notNull(),
        email: pgVarchar('email', { length: 255 }).notNull().unique(),
        passwordHash: pgVarchar('password_hash', { length: 255 }).notNull(),
        role: pgVarchar('role', { length: 50 }),
        createdAt: pgText('created_at').notNull(),
        updatedAt: pgText('updated_at').notNull(),
      }),

      items: pgTable('items', {
        id: pgVarchar('id', { length: 255 }).primaryKey(),
        name: pgVarchar('name', { length: 255 }).notNull(),
        description: pgText('description'),
        type: pgVarchar('type', { length: 50 }).notNull(),
        path: pgText('path').notNull(),
        userId: pgVarchar('user_id', { length: 255 }).notNull(),
        diagramData: pgText('diagram_data'),
        status: pgVarchar('status', { length: 50 }).notNull().default('active'),
        maxBuildsToKeep: pgInteger('max_builds_to_keep').default(50),
        maxLogDays: pgInteger('max_log_days').default(30),
        createdAt: pgText('created_at').notNull(),
        updatedAt: pgText('updated_at').notNull(),
      }),

      envVariables: pgTable('env_variables', {
        id: pgVarchar('id', { length: 255 }).primaryKey(),
        key: pgVarchar('key', { length: 255 }).notNull().unique(),
        value: pgText('value').notNull(),
        description: pgText('description'),
        isSecret: pgVarchar('is_secret', { length: 10 }).notNull().default('false'),
        createdAt: pgText('created_at').notNull(),
        updatedAt: pgText('updated_at').notNull(),
      }),

      credentialVault: pgTable('credential_vault', {
        id: pgVarchar('id', { length: 255 }).primaryKey(),
        name: pgVarchar('name', { length: 255 }).notNull(),
        type: pgVarchar('type', { length: 50 }).notNull(),
        description: pgText('description'),
        username: pgVarchar('username', { length: 255 }),
        password: pgText('password'),
        token: pgText('token'),
        privateKey: pgText('private_key'),
        certificate: pgText('certificate'),
        fileData: pgText('file_data'),
        fileName: pgVarchar('file_name', { length: 255 }),
        fileMimeType: pgVarchar('file_mime_type', { length: 100 }),
        url: pgVarchar('url', { length: 500 }),
        environment: pgVarchar('environment', { length: 50 }),
        tags: pgText('tags'),
        customFields: pgText('custom_fields'),
        expiresAt: pgText('expires_at'),
        lastUsed: pgText('last_used'),
        isActive: pgVarchar('is_active', { length: 10 }).notNull().default('true'),
        createdAt: pgText('created_at').notNull(),
        updatedAt: pgText('updated_at').notNull(),
      }),

      passwordVault: pgTable('password_vault', {
        id: pgVarchar('id', { length: 255 }).primaryKey(),
        name: pgVarchar('name', { length: 255 }).notNull(),
        username: pgVarchar('username', { length: 255 }),
        password: pgText('password').notNull(),
        url: pgVarchar('url', { length: 500 }),
        description: pgText('description'),
        createdAt: pgText('created_at').notNull(),
        updatedAt: pgText('updated_at').notNull(),
      }),

      systemSettings: pgTable('system_settings', {
        id: pgVarchar('id', { length: 255 }).primaryKey(),
        category: pgVarchar('category', { length: 100 }).notNull(),
        key: pgVarchar('key', { length: 255 }).notNull().unique(),
        value: pgText('value'),
        defaultValue: pgText('default_value'),
        type: pgVarchar('type', { length: 50 }).notNull(),
        options: pgText('options'),
        label: pgVarchar('label', { length: 255 }).notNull(),
        description: pgText('description'),
        required: pgVarchar('required', { length: 10 }).notNull().default('false'),
        readonly: pgVarchar('readonly', { length: 10 }).notNull().default('false'),
        createdAt: pgText('created_at').notNull(),
        updatedAt: pgText('updated_at').notNull(),
      }),

      agents: pgTable('agents', {
        id: pgVarchar('id', { length: 255 }).primaryKey(),
        name: pgVarchar('name', { length: 255 }).notNull(),
        description: pgText('description'),
        token: pgVarchar('token', { length: 255 }).notNull().unique(),
        maxConcurrentJobs: pgInteger('max_concurrent_jobs').notNull().default(1),
        hostname: pgVarchar('hostname', { length: 255 }),
        platform: pgVarchar('platform', { length: 50 }),
        architecture: pgVarchar('architecture', { length: 50 }),
        capabilities: pgText('capabilities'),
        version: pgVarchar('version', { length: 50 }),
        systemInfo: pgText('system_info'),
        status: pgVarchar('status', { length: 50 }).notNull().default('offline'),
        currentJobs: pgInteger('current_jobs').notNull().default(0),
        lastHeartbeat: pgText('last_heartbeat'),
        ipAddress: pgVarchar('ip_address', { length: 45 }),
        firstConnectedAt: pgText('first_connected_at'),
        totalBuilds: pgInteger('total_builds').notNull().default(0),
        tags: pgText('tags'),
        notes: pgText('notes'),
        createdAt: pgText('created_at').notNull(),
        updatedAt: pgText('updated_at').notNull(),
      }),

      builds: pgTable('builds', {
        id: pgVarchar('id', { length: 255 }).primaryKey(),
        projectId: pgVarchar('project_id', { length: 255 }).notNull(),
        buildNumber: pgInteger('build_number').notNull(),
        agentId: pgVarchar('agent_id', { length: 255 }),
        agentName: pgVarchar('agent_name', { length: 255 }),
        jobId: pgVarchar('job_id', { length: 255 }),
        trigger: pgVarchar('trigger', { length: 50 }).notNull(),
        status: pgVarchar('status', { length: 50 }).notNull(),
        message: pgText('message'),
        startedAt: pgText('started_at').notNull(),
        finishedAt: pgText('finished_at'),
        duration: pgInteger('duration'),
        nodeCount: pgInteger('node_count'),
        nodesExecuted: pgInteger('nodes_executed'),
        gitBranch: pgVarchar('git_branch', { length: 255 }),
        gitCommit: pgVarchar('git_commit', { length: 255 }),
        metadata: pgText('metadata'),
        createdAt: pgText('created_at').notNull(),
        updatedAt: pgText('updated_at').notNull(),
      }),

      buildLogs: pgTable('build_logs', {
        id: pgVarchar('id', { length: 255 }).primaryKey(),
        buildId: pgVarchar('build_id', { length: 255 }).notNull(),
        nodeId: pgVarchar('node_id', { length: 255 }),
        level: pgVarchar('level', { length: 20 }).notNull(),
        message: pgText('message').notNull(),
        command: pgText('command'),
        output: pgText('output'),
        timestamp: pgText('timestamp').notNull(),
        sequence: pgInteger('sequence').notNull(),
        source: pgVarchar('source', { length: 50 }).notNull().default('system'),
        metadata: pgText('metadata'),
        createdAt: pgText('created_at').notNull(),
      }),

      cronJobs: pgTable('cron_jobs', {
        id: pgVarchar('id', { length: 255 }).primaryKey(),
        projectId: pgVarchar('project_id', { length: 255 }).notNull(),
        cronNodeId: pgVarchar('cron_node_id', { length: 255 }).notNull(),
        cronNodeLabel: pgVarchar('cron_node_label', { length: 255 }).notNull(),
        cronExpression: pgVarchar('cron_expression', { length: 100 }).notNull(),
        enabled: pgVarchar('enabled', { length: 10 }).notNull().default('true'),
        nodes: pgText('nodes').notNull(),
        edges: pgText('edges').notNull(),
        lastRun: pgText('last_run'),
        createdAt: pgText('created_at').notNull(),
        updatedAt: pgText('updated_at').notNull(),
      })
    }
  } else {
    // SQLite schema

    
    return {
      users: sqliteTable('users', {
        id: text('id').primaryKey(),
        name: text('name').notNull(),
        email: text('email').notNull().unique(),
        passwordHash: text('password_hash').notNull(),
        role: text('role'),
        createdAt: text('created_at').notNull(),
        updatedAt: text('updated_at').notNull(),
      }),

      items: sqliteTable('items', {
        id: text('id').primaryKey(),
        name: text('name').notNull(),
        description: text('description'),
        type: text('type').notNull(),
        path: text('path').notNull(),
        userId: text('user_id').notNull(),
        diagramData: text('diagram_data'),
        status: text('status').notNull().default('active'),
        maxBuildsToKeep: integer('max_builds_to_keep').default(50),
        maxLogDays: integer('max_log_days').default(30),
        createdAt: text('created_at').notNull(),
        updatedAt: text('updated_at').notNull(),
      }),

      envVariables: sqliteTable('env_variables', {
        id: text('id').primaryKey(),
        key: text('key').notNull().unique(),
        value: text('value').notNull(),
        description: text('description'),
        isSecret: text('is_secret').notNull().default('false'),
        createdAt: text('created_at').notNull(),
        updatedAt: text('updated_at').notNull(),
      }),

      credentialVault: sqliteTable('credential_vault', {
        id: text('id').primaryKey(),
        name: text('name').notNull(),
        type: text('type').notNull(),
        description: text('description'),
        username: text('username'),
        password: text('password'),
        token: text('token'),
        privateKey: text('private_key'),
        certificate: text('certificate'),
        fileData: text('file_data'),
        fileName: text('file_name'),
        fileMimeType: text('file_mime_type'),
        url: text('url'),
        environment: text('environment'),
        tags: text('tags'),
        customFields: text('custom_fields'),
        expiresAt: text('expires_at'),
        lastUsed: text('last_used'),
        isActive: text('is_active').notNull().default('true'),
        createdAt: text('created_at').notNull(),
        updatedAt: text('updated_at').notNull(),
      }),

      passwordVault: sqliteTable('password_vault', {
        id: text('id').primaryKey(),
        name: text('name').notNull(),
        username: text('username'),
        password: text('password').notNull(),
        url: text('url'),
        description: text('description'),
        createdAt: text('created_at').notNull(),
        updatedAt: text('updated_at').notNull(),
      }),

      systemSettings: sqliteTable('system_settings', {
        id: text('id').primaryKey(),
        category: text('category').notNull(),
        key: text('key').notNull().unique(),
        value: text('value'),
        defaultValue: text('default_value'),
        type: text('type').notNull(),
        options: text('options'),
        label: text('label').notNull(),
        description: text('description'),
        required: text('required').notNull().default('false'),
        readonly: text('readonly').notNull().default('false'),
        createdAt: text('created_at').notNull(),
        updatedAt: text('updated_at').notNull(),
      }),

      agents: sqliteTable('agents', {
        id: text('id').primaryKey(),
        name: text('name').notNull(),
        description: text('description'),
        token: text('token').notNull().unique(),
        maxConcurrentJobs: integer('max_concurrent_jobs').notNull().default(1),
        hostname: text('hostname'),
        platform: text('platform'),
        architecture: text('architecture'),
        capabilities: text('capabilities'),
        version: text('version'),
        systemInfo: text('system_info'),
        status: text('status').notNull().default('offline'),
        currentJobs: integer('current_jobs').notNull().default(0),
        lastHeartbeat: text('last_heartbeat'),
        ipAddress: text('ip_address'),
        firstConnectedAt: text('first_connected_at'),
        totalBuilds: integer('total_builds').notNull().default(0),
        tags: text('tags'),
        notes: text('notes'),
        createdAt: text('created_at').notNull(),
        updatedAt: text('updated_at').notNull(),
      }),

      builds: sqliteTable('builds', {
        id: text('id').primaryKey(),
        projectId: text('project_id').notNull(),
        buildNumber: integer('build_number').notNull().default(0),
        agentId: text('agent_id'),
        agentName: text('agent_name'),
        jobId: text('job_id'),
        trigger: text('trigger').notNull(),
        status: text('status').notNull(),
        message: text('message'),
        startedAt: text('started_at').notNull(),
        finishedAt: text('finished_at'),
        duration: integer('duration'),
        nodeCount: integer('node_count'),
        nodesExecuted: integer('nodes_executed'),
        gitBranch: text('git_branch'),
        gitCommit: text('git_commit'),
        metadata: text('metadata'),
        createdAt: text('created_at').notNull(),
        updatedAt: text('updated_at').notNull(),
      }),

      buildLogs: sqliteTable('build_logs', {
        id: text('id').primaryKey(),
        buildId: text('build_id').notNull(),
        nodeId: text('node_id'),
        level: text('level').notNull(),
        message: text('message').notNull(),
        command: text('command'),
        output: text('output'),
        timestamp: text('timestamp').notNull(),
        sequence: integer('sequence').notNull(),
        source: text('source').notNull().default('system'),
        metadata: text('metadata'),
        createdAt: text('created_at').notNull(),
      }),

      cronJobs: sqliteTable('cron_jobs', {
        id: text('id').primaryKey(),
        projectId: text('project_id').notNull(),
        cronNodeId: text('cron_node_id').notNull(),
        cronNodeLabel: text('cron_node_label').notNull(),
        cronExpression: text('cron_expression').notNull(),
        enabled: text('enabled').notNull().default('true'),
        nodes: text('nodes').notNull(),
        edges: text('edges').notNull(),
        lastRun: text('last_run'),
        createdAt: text('created_at').notNull(),
        updatedAt: text('updated_at').notNull(),
      })
    }
  }
}